### PR TITLE
Fix cidr parsing where masks cannot be integerised

### LINKED ISSUE #111: Unsanitised argument to atoi() in hostmask parsing code
`parse_netmask()` in `src/hostmask.c` does not validate that the values that it passes to `atoi()` are valid numerical values. This means that an invalid netmask could be passed (such as `192.168.0.1/i`) which would cause `atoi()` to return zero. The accidental mass k-lining on freenode on 17th August 2017 in response to a spambot attack was partly due to an invalid netmask being passed to the IRC server which was not sanitised.

### PR DESCRIPTION
**Pull request by AbstractBeliefs**
fixes #111

### CODE REVIEW

**Comment by edk0** [comment]
@AbstractBeliefs could we fix this in `match.c` too?

**Comment by AbstractBeliefs** [comment]
Based on testnet fiddling:

#### Negative test cases
| kline             | target      | intention | result             |
|-------------------|-------------|-----------|:------------------:|
| 11.22.33.44       | 55.66.77.88 | no hit    | :white_check_mark: |
| 11.22.33.44/abc   | 55.66.77.88 | no hit    | :white_check_mark: |
| 11.22.33.44/16abc | 55.66.77.88 | no hit    | :white_check_mark: |
| 11.22.33.44/16    | 55.66.77.88 | no hit    | :white_check_mark: |

#### Positive test cases
| kline             | target      | intention | result             |
|-------------------|-------------|-----------|:------------------:|
| 55.66.77.88       | 55.66.77.88 | hit       | :white_check_mark: |
| 55.66.77.88/abc   | 55.66.77.88 | hit       | :white_check_mark: |
| 55.66.77.88/16abc | 55.66.77.88 | hit       | :white_check_mark: |
| 55.66.77.88/16    | 55.66.77.88 | hit       | :white_check_mark: |

I think this is the correct behaviour and we should be able to merge this into prod unless anyone else spots an issue.

**Comment by bigpresh** [comment]
Personally, I'd *prefer* an invalid CIDR mask to be rejected, rather than assumed to be a /32, but assuming it meant /32 is *far* better than the current behaviour :)

**Comment by emersonveenstra** [comment]
I would lean towards rejecting it as well, since that's what we do for all other instances where a kline is badly formed

**Comment by AbstractBeliefs** [comment]
To be honest, if we want to reject it I'd suggest opening a new issue, as the code in question doesn't have an obvious way to return failure, so either we'd need to factor in a failure retval, or do preprocessing meaning we're confident that the thing we're passing in is actually valid.

**Comment by bigpresh** [comment]
Yeah, I'd be in favour of this being merged as it certainly makes the behaviour less batshit, then maybe consider further improvements to reject if invalid later if we find a clean way to do so without re-engineering too much.  Maybe this change could trigger a snote to explain what happened, though? e.g. "Invalid CIDR mask $foo/$bar treated as $foo" or similar?  Doing it entirely silently feels wrong.

**Comment by xnrand** [comment]
There appears to be an integer underflow with large negative numbers (n-2^32). 
Example: `@1.2.3.4/-4294967296` (n=0) matches all IPv4 on testnet.

**Comment by AbstractBeliefs** [comment]
The most obvious response would be to reject any bans less than some fixed (or configurable) limit. I was thinking /8 but this could also be configurable or simply also >0. Who has opinions on this?

**Comment by mquin** [comment]
For k-lines there is already a somewhat adjustable minimum mask length - https://github.com/freenode/ircd-seven/blob/cbf070e4720cf6ab4a10bd5f2fc06b7459b26c12/src/s_conf.c#L983

**Pull request merged**
